projectName: roboshop
appPort: "8080"
serviceType: ClusterIP
replicas: 2


job:
  enabled: false

ingress:
  enabled: false

istio:
  mode: STRICT
  principals: ["cluster.local/ns/example2/sa/debug", "cluster.local/ns/example2/sa/debug1"]

