apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    project: {{ .Values.projectName }}
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      project: {{ .Values.projectName }}
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        project: {{ .Values.projectName }}
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:latest
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}

