---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  mtls:
    mode: {{ .Values.istio.mode }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          {{- range .Values.istio.principals }}
          - {{ . | quote }}
          {{- end }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  action: DENY
  rules:
  - from:
    - source:
        notPrincipals:
          {{- range .Values.istio.principals }}
          - {{ . | quote }}
          {{- end }}



