{{ if .Values.job.enabled | default false }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-schema
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.appName }}-schema
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}-db-image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}
      restartPolicy: Never
  backoffLimit: 0
{{ end }}
